// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBP_xFtkx5REmaIwTIlrEIXpVwg8rM6TEM',
    appId: '1:567284478969:web:0337f3101447d41eda4328',
    messagingSenderId: '567284478969',
    projectId: 'zestplus-6857a',
    authDomain: 'zestplus-6857a.firebaseapp.com',
    storageBucket: 'zestplus-6857a.firebasestorage.app',
    measurementId: 'G-D6LWPJBJX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCf7Amnn3xRjB65Y_z_UVwRtky95jl0hnM',
    appId: '1:567284478969:android:78d06f4906dff835da4328',
    messagingSenderId: '567284478969',
    projectId: 'zestplus-6857a',
    storageBucket: 'zestplus-6857a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJwqFxzOroDpNv9lN_INkFjN6GtIPI2RA',
    appId: '1:567284478969:ios:f58e03d0b62fc7e7da4328',
    messagingSenderId: '567284478969',
    projectId: 'zestplus-6857a',
    storageBucket: 'zestplus-6857a.firebasestorage.app',
    iosBundleId: 'com.example.zestMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJwqFxzOroDpNv9lN_INkFjN6GtIPI2RA',
    appId: '1:567284478969:ios:f58e03d0b62fc7e7da4328',
    messagingSenderId: '567284478969',
    projectId: 'zestplus-6857a',
    storageBucket: 'zestplus-6857a.firebasestorage.app',
    iosBundleId: 'com.example.zestMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBP_xFtkx5REmaIwTIlrEIXpVwg8rM6TEM',
    appId: '1:567284478969:web:f41b9e131aab5020da4328',
    messagingSenderId: '567284478969',
    projectId: 'zestplus-6857a',
    authDomain: 'zestplus-6857a.firebaseapp.com',
    storageBucket: 'zestplus-6857a.firebasestorage.app',
    measurementId: 'G-3W5QMMB5Y0',
  );

}